// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_DAx8ivhMcukZjg-AbSLiFsfyOPA8bcA',
    appId: '1:85432995468:web:27e96fd29a744d30ee35a9',
    messagingSenderId: '85432995468',
    projectId: 'nexabook-aed13',
    authDomain: 'nexabook-aed13.firebaseapp.com',
    storageBucket: 'nexabook-aed13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7IJdJ1o7LohmOseGEMkXyGzP_vhyTpls',
    appId: '1:85432995468:android:455b369f63e5810aee35a9',
    messagingSenderId: '85432995468',
    projectId: 'nexabook-aed13',
    storageBucket: 'nexabook-aed13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtK0vMnvziI3KRF-4UrDUIN1nVM59T7yw',
    appId: '1:85432995468:ios:4570ddf45d750583ee35a9',
    messagingSenderId: '85432995468',
    projectId: 'nexabook-aed13',
    storageBucket: 'nexabook-aed13.firebasestorage.app',
    iosBundleId: 'com.example.nexabook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtK0vMnvziI3KRF-4UrDUIN1nVM59T7yw',
    appId: '1:85432995468:ios:4570ddf45d750583ee35a9',
    messagingSenderId: '85432995468',
    projectId: 'nexabook-aed13',
    storageBucket: 'nexabook-aed13.firebasestorage.app',
    iosBundleId: 'com.example.nexabook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_DAx8ivhMcukZjg-AbSLiFsfyOPA8bcA',
    appId: '1:85432995468:web:5742850f11b88b7bee35a9',
    messagingSenderId: '85432995468',
    projectId: 'nexabook-aed13',
    authDomain: 'nexabook-aed13.firebaseapp.com',
    storageBucket: 'nexabook-aed13.firebasestorage.app',
  );
}
